os: linux

language: cpp

stages:
  - build
  - name: deploy
    if: branch = stable


jobs:
  include:
    - stage: build
      name: "Linux Bionic Build"
      os: linux
      dist: bionic
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y build-essential cmake xorg-dev libgl1-mesa-dev libfreetype6-dev
      install:
        - mkdir build && cd build
        - cmake ..
      script:
        - cmake --build .
    - stage: build
      name: "Linux Xenial Build"
      os: linux
      dist: xenial
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y build-essential cmake xorg-dev libgl1-mesa-dev libfreetype6-dev
      install:
        - mkdir build && cd build
        - cmake ..
      script:
        - cmake --build .
    - stage: build
      name: "MacOS Build"
      os: osx
      install:
        - mkdir build && cd build
        - cmake ..
      script:
        - cmake --build .
    - stage: build
      name: "Windows MinGW Build"
      os: windows
      install:
        - choco upgrade --no-progress -y msys2
        - export msys2='cmd //C RefreshEnv.cmd '
        - export msys2+='& set MSYS=winsymlinks:nativestrict '
        - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        - export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
        - export msys2+=" -msys2 -c \$\* --"
        - $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain cmake
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        - taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        - export PATH=/C/tools/msys64/mingw64/bin:$PATH
        - export MAKE=mingw32-make  # so that Autotools can find it
      install:
        - mkdir build && cd build
        - cmake ..
      script:
        - cmake --build .
    - stage: build
      name: "Windows MVS 2017 Build"
      os: windows
      install:
        - mkdir build && cd build
        - cmake -G "Visual Studio 15 2017" ..
      script:
        - cmake --build .
    - stage: deploy
      name: "Deploy Test"
      os: linux
      before_deploy: 
        - echo Bonjour > text.txt
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        file:
            - DevOps-app
        on:
          branch: stable

